### ISSUE TITLE
pg13 image timescale-tunes for pg11

### ISSUE THREAD

**Issue by elbaro** [timescale/timescaledb-docker-ha#121] opened 2021-06-16 09:08 UTC
The image `timescale/timescaledb-ha:pg13.2-ts2.2.0-oss-p0 ` has the command to tune for pg11.

```
│     Command:                                                                                                        
│       sh                                                                                                            
│       -c                                                                                                            
│       set -e                                                                                                        
│       [ $CPUS -eq 0 ]   && CPUS="${RESOURCES_CPU_LIMIT}"                                                            
│       [ $MEMORY -eq 0 ] && MEMORY="${RESOURCES_MEMORY_LIMIT}"                                                       
│                                                                                                                     
│       if [ -f "${PGDATA}/postgresql.base.conf" ] && ! grep "${INCLUDE_DIRECTIVE}" postgresql.base.conf -qxF; then   
│         echo "${INCLUDE_DIRECTIVE}" >> "${PGDATA}/postgresql.base.conf"                                             
│       fi                                                                                                            
│                                                                                                                     
│       touch "${TSTUNE_FILE}"                                                                                        
│       timescaledb-tune -quiet -pg-version 11 -conf-path "${TSTUNE_FILE}" -cpus "${CPUS}" -memory "${MEMORY}MB" \    
│          -yes
```

`timescaledb-tune` has [listed](https://github.com/timescale/timescaledb-tune/blob/f6b74b85e3378b1b07e363daf89a8fe1d388c665/pkg/tstune/utils.go) pg13 as a valid version, so I guess it's supported:

```go
var ValidPGVersions = []string{
	pgutils.MajorVersion13,
	pgutils.MajorVersion12,
	pgutils.MajorVersion11,
	pgutils.MajorVersion10,
	pgutils.MajorVersion96,
}
```

The dockerfile also has
![image](https://user-images.githubusercontent.com/1851290/122191486-c0036e80-cecd-11eb-8a1d-50c3bbac9eef.png)

What is going on here? tune does not support 12 or 13?

**Comment by feikesteenbergen** [comment] 2021-06-21 06:22
It's been a while, however this snippet:

```shell
timescaledb-tune -quiet -pg-version 11
```

Was introduced in 5095fde1efcc6b6751cd2114ae894b0752708221, as `timescaledb-tune` did not support PostgreSQL 12 at that time.

Will fix.

**Comment by feikesteenbergen** [comment] 2021-06-21 06:31
That means the issue is due to this:

https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/templates/statefulset-timescaledb.yaml#L96

Which is not part of this repository, but of the Helm Charts.

Closing this issue in favor of the issue in the Helm Charts repository:

https://github.com/timescale/timescaledb-kubernetes/issues/294

**Closed by feikesteenbergen** 2021-06-21 06:31 UTC
